ARG BASE_IMAGE="ghcr.io/gbraad-homelab/private-base"
ARG BASE_VERSION="latest"

FROM ${BASE_IMAGE}:${BASE_VERSION}

# Create a default 'admin' user with the specified password.
# Add it to the 'wheel' group to allow for running sudo commands.
ARG ADMIN_PASSWD
# hadolint ignore=DL4006
RUN if [ -z "${ADMIN_PASSWD}" ] ; then \
        echo "ADMIN_PASSWD is a mandatory build argument" && exit 1 ; \
    fi \
    && useradd -m -d /var/home/admin -G wheel admin \
    && echo "admin:${ADMIN_PASSWD}" | chpasswd

RUN dnf install -y git git-lfs openssh-server \
    && dnf clean all \
    && rm -rf /var/cache/yum \
    && curl -fsSL https://codeberg.org/forgejo/forgejo/releases/download/v10.0.0/forgejo-10.0.0-linux-amd64 -o /usr/local/bin/forgejo \
    && chmod +x /usr/local/bin/forgejo \
    && curl -fsSL https://codeberg.org/forgejo/forgejo/raw/branch/forgejo/contrib/systemd/forgejo.service -o /etc/systemd/system/forgejo.service \
    && sed -i 's/HOME=\/home\/git/HOME=\/var\/home\/git/' /etc/systemd/system/forgejo.service \
    && systemctl enable forgejo.service \
    && systemctl enable sshd.service \
    && chmod 640 /etc/shadow \
    && mkdir -p /var/home/ \
    && groupadd --system git \
    && useradd --system --shell /bin/bash --comment 'Git Version Control' --gid git --home-dir /var/home/git --create-home git \
    && mkdir /var/lib/forgejo \
    && chown git:git /var/lib/forgejo \
    && chmod 750 /var/lib/forgejo \
    && mkdir /etc/forgejo \
    && chown root:git /etc/forgejo \
    && chmod 770 /etc/forgejo
