name: tailscale-ssh-warpbuild

on:
  workflow_dispatch:

jobs:
  remote-test:
    name: Tailscale SSH Machine - WarpBuild
    uses: ./.github/workflows/reusable-tailscale-ssh.yml
    with:
      runs-on: "warp-ubuntu-latest-x64-2x"
      image: "ghcr.io/gbraad-homelab/forgejo:latest"
      hostname: "homelab-forgejo"
    secrets: inherit
